mem:
  # If your HPC resource has a high memory capacity node you can set this to
  # TRUE and specify the amount of memory per core (e.g. if a node has 260 gb of
  # RAM and 10 cores it would be 26).
  big_mem_avail: FALSE
  big_mem_per_core_gb: 26
  # Memory per core of your computing resource.
  normal_mem_per_core_gb: 4
# Path to a temporary directoru to write to.
tmp_dir: tmp
raws:
  # Path to a assembly fasta.
  assembly: "path/to/assembly"
  # Path to a bam file to calculate depth from (single sample mode only atm).
  # Leave empty if you have an average depth per contig file to supply to bnny.
  metagenomics_alignment: ""
  # Path to an average depth per contig tsv file. Leave empty if you supply a
  # bam file for binny to calculate average contig depth from.
  contig_depth: ""
# Sample name
sample: "test"
# Path to desired output dir binny should create and store results in.
outputdir: "path/to/output/dir"
# Path to binny dbs, leave at default if you performed the defaulty install.
db_path: "../db"
binning:
  binny:
    # Input a list, e.g. '2,3,4'.
    kmers: '2,3,4'
    # Minimum contig length.
    cutoff: 500
    # Minimum length of contigs containing CheckM markers.
    cutoff_marker: 0
    # Maximum number of contigs binny uses. If the number of available contigs after minimum size filtering exceeds this,
    # binny will increase the minimum size threshold until the maximum is reached. Prevents use of excessive amounts of
    # memory on large assemblies. Default should ensure adequate performance, adjust e.g. according to available memory.
    max_n_contigs: 3.5e5
    # Distance metric for opentSNE and HDBSCAN.
    distance_metric: 'manhattan'
    embedding:
      # Maximum number of binny iterations.
      max_iterations: 50
      # Number of iterations with perplexity: (n contigs) / 100.
      tsne_early_exag_iterations: 250
      # Number of iterations with perplexity 1.
      tsne_main_iterations: 750
    clustering:
      # Increasing the HDBSCAN cluster selection epsilon beyond 0.5
      # is not advised as it might massively increase run time, but it might
      # help recover genoems that would be missed with lower settings.
      hdbscan_epsilon: 0.25
      # Adapted from the HDBSCAN manual: 'Measure of how conservative the
      # clustering should be. With larger values, more points will be declared
      # as noise, and clusters will be restricted to progressively more dense areas.'.
      hdbscan_min_samples: 2
      # Use depth as additional dimension during the initial clustering.
      include_depth_initial: 'False'
      # Use depth as additional dimension during the main clusterings.
      include_depth_main: 'True'
    bin_quality:
      # Minimum value binny will lower completeness to while running. It will
      # start at 90.
      completeness: 80
      # Minimum purity for bins to be selected.
      purity: 85
