mem:
  big_mem_avail: FALSE
  normal_mem_per_core_gb: 8
  big_mem_per_core_gb: 36
tmp_dir: tmp
raws:
  Contigs: "test/contigs_3bins.fa"
  Alignment_metagenomics: "test/reads_3bins.bam"
  Contig_depth: ""
sample: test
outputdir: "test_must"
db_path: "database"
binning:
  binny:
    kmers: '2,3,4' # Input a list, e.g. '2,3,4'
    cutoff: 1000
  filtering:
    completeness: 70
    purity: 90
