mem:
  big_mem_avail: FALSE
  normal_mem_per_core_gb: 4
  big_mem_per_core_gb: 26
tmp_dir: tmp
raws:
  Contigs: "test/assembly.fasta"
  Alignment_metagenomics: "test/mg.reads.sorted.bam"
  Contig_depth: ""
sample: test
outputdir: "binny_initialized"
db_path: "database"
binning:
  binny:
    kmers: '2,3,4' # Input a list, e.g. '2,3,4'
    cutoff: 1000
  filtering:
    completeness: 70
    purity: 90
